config/routes.rb
Rails.application.routes.draw do

	namespace :casein do
		resources :posts
	end

  resources :posts

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/casein/posts_controller.rb
# Scaffolding generated by Casein v5.1.1.3

module Casein
  class PostsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Posts'
  		@posts = Post.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View post'
      @post = Post.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new post'
    	@post = Post.new
    end

    def create
      @post = Post.new post_params
    
      if @post.save
        flash[:notice] = 'Post created'
        redirect_to casein_posts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new post'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update post'
      
      @post = Post.find params[:id]
    
      if @post.update_attributes post_params
        flash[:notice] = 'Post has been updated'
        redirect_to casein_posts_path
      else
        flash.now[:warning] = 'There were problems when trying to update this post'
        render :action => :show
      end
    end
 
    def destroy
      @post = Post.find params[:id]

      @post.destroy
      flash[:notice] = 'Post has been deleted'
      redirect_to casein_posts_path
    end
  
    private
      
      def post_params
        params.require(:post).permit(:title, :contents, :publication_date, :preview_image_url, :preview)
      end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @markdown = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML,
      :autolink => true, :space_after_headers => true)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Cerebri/o'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for casein_posts_path
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end
    
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/casein/layouts/_tab_navigation.html.erb
<!-- NOTE: the casein:scaffold generator automatically appends new controllers to this file. The SCAFFOLD_INSERT line must NOT be removed -->
<!-- SCAFFOLD_INSERT -->
<li id="tab-posts"><%= link_to "Posts", casein_posts_path %></li>

app/views/casein/layouts/_top_navigation.html.erb
<!-- NOTE: add "hidden-xs hidden-sm" class to li elements you want to be hidden at small browser widths -->
<!-- e.g. <li class="hidden-xs hidden-sm"><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li> -->

<li><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li>

app/views/casein/posts/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->
<script type="text/javascript" src='<%=asset_path("bootstrap-markdown.js")%>'></script>
<link rel="stylesheet" type="text/css" href='<%=asset_path("bootstrap-markdown.min.css")%>' />

<div class="row">
	<div class="col-lg-12">
		<%= casein_text_field f, f.object, :title %>
	</div>
	
</div>

<div class="row">
	<div class="col-lg-12">
		<%= casein_text_area f, f.object, :contents,  "data-provide" => "markdown" %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_area f, f.object, :preview %>
	</div>
	
	<div class="col-lg-6">
		<%= casein_url_field f, f.object, :preview_image_url %>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<%= casein_datetime_select f, f.object, :publication_date %>
	</div>
</div>

app/views/casein/posts/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Title", :title %></th>
			<th><%= casein_sort_link "Contents", :contents %></th>
			<th><%= casein_sort_link "Publication date", :publication_date %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% posts.each do |post| %>
		<tr>
			<td><%= casein_table_cell_link post.title, casein_post_path(post) %></td>
			<td><%= casein_table_cell_link post.contents, casein_post_path(post) %></td>
			<td><%= casein_table_cell_link post.publication_date, casein_post_path(post) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_post_path(post), :method => :delete, :data => { :confirm => "Are you sure you want to delete this post?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/posts/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>Posts<%= casein_pagination_details @posts %></h2>

<%= render :partial => 'casein/posts/table', :locals => { :posts => @posts } %>

<div class="text-center">
	<%= will_paginate @posts %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new post".html_safe, new_casein_post_path %></li>

<% end %>

app/views/casein/posts/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>Add a new post</h2>

<%= form_for @post, :url => casein_posts_path do |f| %>
	
	<%= render :partial => 'casein/posts/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_posts_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new post", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_posts_path %></li>
<% end %>

app/views/casein/posts/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>View post</h2>

<%= form_for @post, :url => casein_post_path(@post) do |f| %>

	<%= render :partial => 'casein/posts/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_posts_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_posts_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cerebrio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Cerebri/o</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav">
        <li><a href="<%= posts_path %>">Recent posts</a></li>
        <li><%= link_to 'About us', page_path('about') %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Technology<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">BCI</a></li>
            <li><a href="#">Neurofeedback</a></li>
            <li><a href="#">Neuroplasticity</a></li>
            <li><a href="#">EEG</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Our projects<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Brain toys</a></li>
          </ul>
        </li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Contacts', page_path('contacts') %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>Coming soon...</h1>
</div>

app/views/pages/contacts.html.erb
<div class="container">
  <h1>Coming soon...</h1>
</div>

app/views/posts/index.html.erb
<div class='jumbotron'>
  
    <%= image_tag("logo_big.png", width: 408)%>
    <h1>Where waves push forward</h1>
    <p>We are an ambitious startup company developing products using BCI technology.</p>
    <p>We use inexpensive and non-invasive EEG headsets to send brain activity data to the computer or other device.</p>

  
</div>

<div class='container'>
  <p id="notice"><%= notice %></p>

  <h1>Recent posts</h1>
  <% @posts.each do |post| %>
    <div class='col-md-4'>
    <div class='post-preview' style='background:  linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url("<%= post.preview_image_url%>")'>
      <div class='preview-contents'>
        <h2><%= post.title %></h2>
        <%= simple_format(post.preview) %>
      </div>
      <a class="btn btn-default" href="<%= post_path(post) %>" role="button">Read more »</a>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class='container'> 
  <p id="notice"><%= notice %></p>
  <h1><%= @post.title %></h1>
  <%= @markdown.render(@post.contents).html_safe %>
  <%= link_to 'Back', posts_path %>
</div>